name: Update Latest Commit
on:
  push:
    branches: [ main ]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Delete old 'latest' tag
      run: |
        git tag -d latest || true
        git push origin --delete latest || true

    - name: Create new 'latest' tag
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git tag latest HEAD -f
        git push origin latest -f
